# AGL specific package configuration
#
# Add systemd configuration

SHAREDIR = "${datadir}/basesystem"
INCLUDEDIR = "${includedir}/basesystem"
CONFDIR = "${sysconfdir}/basesystem"
LOCALDIR = "/var/local/lib/basesystem"
AGL_BRANCH = "sandbox/Riku.Nomoto/WIP_20201201"

#BASESYSTEM_REVISION = "7ab637d7f01e712488deab0d318443ed9a81d5ae"
BASESYSTEM_REVISION = "192f2ab881c2ecc586cd0f7551887a7759272a65"

